<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>GrenadeOnlyFF</AssemblyName>
    <RootNamespace>GrenadeOnlyFF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Локальная ссылка на CounterStrikeSharp.dll (положи DLL в libs/) -->
    <Reference Include="CounterStrikeSharp">
      <HintPath>../../libs/CounterStrikeSharp.API.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\pluginsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
